### PR TITLE
Update mandoc

### PR DESCRIPTION
**Pull request by omar-polo**
Hello,

this pr updates mandoc to the latest snapshot.  There were lots of improvements that are very likely worth to have in here too.  I know that the diff is large and I'm just a random guy on the internet: what I did for the first commit was to fetch the latest tarball from the mandoc website and copy its content in `mandoc/`, it should be easy to repeat and ensure that I'm not trying to sneakily add other stuff in there.

Then, I've also integrated the bundled mandoc a bit more.  It's IMHO better to only build the needed compats, and since i was there I've also tweaked the default CFLAGS and LDFLAGS so it's easier to build it.

Tested on OpenBSD 7.1-CURRENT: it builds without any particular effort now :)

### CODE REVIEW

**Comment by omar-polo** [comment]
I forgot to mention a thing, sorry.  Usually, consumers should only use stable releases of mandoc because of course these snapshot are just development version.  However, since the last public release quite a number of crashes were fixed, so I thought it makes more sense in this case to sync to the latest development version.

**Comment by omar-polo** [comment]
i reworked 72f75e5 a bit, it does the same job but a bit better now, without adding any other GNUisms to the Makefile :)

edit: i made a mistake and had to force-push again.  Now every commit should be self-contained.

Note that I can't move the last two commits to a separate PR because they depend on a newer mandoc-portable for MANDOC_COBJS.

**Comment by zigalenarcic** [comment]
I reviewed the changes and accepted the commits (as a rebase). Thank you for updating the library.

**Comment by omar-polo** [comment]
Thanks for reviewing the changes and accepting the PR!  (and also for maintaining this project! :-)

**Pull request merged**
